# Generated by Django 4.0.4 on 2022-05-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabiasque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sabiasquepage',
            name='intro',
            field=models.CharField(max_length=300),
        ),
    ]
