# Generated by Django 4.0.4 on 2022-05-25 15:09

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sabiasque', '0002_alter_sabiasquepage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sabiasquepage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
