# Generated by Django 4.0.4 on 2022-05-27 07:59

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sabiasque', '0004_articlehighlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlehighlight',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
