# Generated by Django 4.0.4 on 2022-05-27 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('sabiasque', '0006_article_delete_articlehighlight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='ArticlePage',
        ),
    ]
