# Generated by Django 3.2.13 on 2022-06-13 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('community', '0003_auto_20220613_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitywellcomepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
    ]
