# Generated by Django 3.2.13 on 2022-06-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogindexpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='web',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
