# Generated by Django 4.0.5 on 2022-06-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_appuser_points_historicalappuser_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
