# Generated by Django 3.2.13 on 2022-06-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0005_auto_20220613_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='taste',
            field=models.ManyToManyField(blank=True, related_name='appuser', to='userManagement.UserTaste'),
        ),
    ]
