# Generated by Django 4.0.4 on 2022-07-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0006_alter_appuser_taste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='taste',
            field=models.ManyToManyField(blank=True, related_name='%(class)s', to='userManagement.usertaste'),
        ),
    ]
