# Generated by Django 3.2.13 on 2022-05-25 08:03

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_auto_20220525_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiespage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
