# Generated by Django 4.0.4 on 2022-06-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('premios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexPremios',
            new_name='IndexPremiosPage',
        ),
    ]
