# Generated by Django 4.0.4 on 2022-06-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premios', '0003_premiopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiopage',
            name='short_title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='premiopage',
            name='value',
            field=models.CharField(default='-1', max_length=6),
        ),
    ]
