# Generated by Django 4.0.4 on 2022-06-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premios', '0004_premiopage_short_title_premiopage_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiopage',
            name='value',
            field=models.CharField(default='0', max_length=6),
        ),
    ]
